### ISSUE TITLE
Choose a project LICENSE

### ISSUE THREAD

**Issue by matshou** [TSSN/Twisted-Tweaks#16]
The project should be licensed with an open-source license so others can have some degree of permission to use the code further then just viewing and forking the repo as granted by [Github TOS](https://help.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users).

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

Read more about what happens when you [don't choose a license](https://choosealicense.com/no-permission/).

I would recommend [choosing an open-source license](https://choosealicense.com/) that at least permits **modification**, **distribution** and **private use**. My personal recommendation always tends to be [GNU GPL](https://choosealicense.com/licenses/gpl-3.0/) which is a strong copyleft license but a pushover license like [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) might be more appropriate if we think the mod is not unique enough and would thus benefit more from less strict conditions and limitations.

**Comment by artdude543** [comment]
To date, since I started the mod the entire project/code is licensed under MIT as seen [here](https://github.com/PuppetzMedia/Twisted-Tweaks/blob/1.12.2/LICENSE).

**Comment by yooksi** [comment]
Oh very sorry about that, don't know how I missed that. Could have swore that I didn't see a license in the repo display bar, sorry for the inconvenience :sweat:

**Comment by artdude543** [comment]
Nah, your all fine. It happens developers lose things all the time xD
