### ISSUE TITLE
Acid burn

### ISSUE THREAD

**Issue by K4N0** [TSSN/Twisted-Tweaks#2]
Acid Burn effect seems to give 10-30 secs to players when eating different items.
"Mojangsters" modpack from the technic launcher

**Comment by artdude543** [comment]
Hmm will look into this but last time we had on bug it was due to a potion id conflict. But I'll check out the code to see if we can prevent the issue. But we don't listen for eating so I guessing it's a potion id conflict or another mod doing weird things.

**Comment by Badcholo** [comment]
yes, eating on my server gives you the well fed potion effect and it gives you a slight regeneration since regeneration has been reduced to about 25%. How can i fix a potion id conflict? i'll check the config for it. How can i see all the potion ids and what they are used for?
Thanks for the quick reply, I really appreciate it. I love the Acid rain effect, it's so amazing!

**Comment by Badcholo** [comment]
Potion Id Sorter has found 2 potion id conflicts.
The first potion is the one that has been overwritten. The second is the potion currently assigned to the id.
This mod has already found all of the available potion id's and assigned one to each conflict. Simply change one of the conflicting potions to the id suggested in the config for the mod that adds the potion.

Potions are listed as:
[Potion 1 Class]:[Potion 1 Name] --> [Potion 2 Class]:[Potion 2 Name]
The mod id is not given but it should be easy to figure out the mod from the class. Just look for the mod name in the class path e.g. "am2.buffs.ArsMagicaPotion" = Ars Magica, "vazkii.botania.common.brew.potion.PotionSoulCross" = Botania, "com.emoniph.witchery.brewing.potions.PotionChilled" = Witchery etc.

Conflict: iguanaman.hungeroverhaul.potion.PotionWellFed:potion.wellfedPotion --> uk.artdude.tweaks.twisted.common.potions.TTPotions:potion.tweaks.twisted.acid.burn at id: 26 Change one of these to 27
Conflict: redgear.brewcraft.effects.EffectVanillaThree:potion.regeneration --> net.tynkyn.common.PotionTYNKYN:potion.blockStep at id: 50 Change one of these to 28

**Comment by Badcholo** [comment]
How do i change a potion id?

**Comment by Badcholo** [comment]
Sry, i'm an idiot, i found the config to change the potion id. 
I was so sure it didn't have a config to change it. omfg i'm such a noob.

**Comment by Badcholo** [comment]
I miss the void pipe so much.
