### ISSUE TITLE
Remove vanilla torches from creative tab

### ISSUE THREAD

**Issue by matshou** [TSSN/Twisted-Tweaks#25]
After completing #22, vanilla torches should be removed from creative tab.

This is so they cannot be used in the game anymore.

**Comment by MindlessPuppetz** [comment]
Vanilla torches should *not* be removed from Creative Tab. If you are in creative, you are bypassing the mechanic anyways and if they want vanilla torches that is up to them. Also, unlit torch + torch paste = vanilla torch in regards to recipes.

**Comment by yooksi** [comment]
Understood, I will not implement this feature.
