### ISSUE TITLE
Liquid Void

### ISSUE THREAD

**Issue by MindlessPuppetz** [TSSN/Twisted-Tweaks#30]
Liquid void does not seem to accept any fluids. v0.9a

Tested with:

Refined Pipes: Pipes will not even connect to the block.

Cyclic: pipes connect but do not push liquid into the block.

Mekanism: Tanks will not push fluids into it.

Vanilla: Bucket will not empty into the block, just places the water against it in the world.

https://cdn.puppetzmedia.com/Hf64Shj6.png

**Comment by Tfarcenim** [comment]
Also fixed as of 0.9b
