### ISSUE TITLE
Mob AI - v0.9a

### ISSUE THREAD

**Issue by MindlessPuppetz** [TSSN/Twisted-Tweaks#31]
Mob AI is not working for attacking blocks.

minecraft:zombie enabled for mobs

    "minecraft:torch",
    "twistedtweaks:torch_unlit",
    "twistedtweaks:torch_glowstone"

all tested against zombie, doesn't not attack any of them.

**Comment by Tfarcenim** [comment]
fixed up in 0.9a
![2020-05-09_23-04-34](https://user-images.githubusercontent.com/44327798/81490120-03f85e80-924c-11ea-92c1-3c61e09c538b.gif)
