### ISSUE TITLE
[Suggestion] Acid Rain per dimension

### ISSUE THREAD

**Issue by davqvist** [TSSN/Twisted-Tweaks#6]
Hi, I'm working on a custom pack and would love to use your mod mainly for the Acid Rain.
But it doesn't work out fully. Could you make it possible to define a dimension white or black list for Acid Rain?

I would appreciate it if you would consider adding that.

**Comment by TacticalUniverse** [comment]
I would love this to be added as well cause then I can disable Acid rain per DIM

**Comment by MindlessPuppetz** [comment]
Added in the latest release. We were unable to test the DIM whitelisting, so please let us know if you encounter any issues.
