### ISSUE TITLE
Whitelist Dim list

### ISSUE THREAD

**Issue by ghost** [TSSN/Twisted-Tweaks#7]
With just the overworld aka 0 in the whitelist, Acid rain still hurts people in other dim. we need somekind of blacklist to stop acid rain of hurting people in other dims

**Comment by Lemonszz** [comment]
What dimension/mod is this happening in?

**Comment by Lemonszz** [comment]
Regardless, I just uploaded 0.6.1 that adds some additional checks. It should be avalible on curse soon. 
Please reopen if it's still broken.
